name: release

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: pnpm build:all

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4

      - run: pnpm install
        #rebuild to ensure the test code is up-to-date
      - run: pnpm build:all
      - run: pnpm test
   
  execute-bash-script:
    if: github.event.pull_request.merged == true && github.base_ref == 'master' && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la

      - name: Set permissions for the script
        run: chmod +x ./scripts/releaser.sh

      - name: Execute deployment script
        shell: bash
        run: ./scripts/releaser.sh